version: "3"
services:
  baroque:
#    build: .
    image: "node:8"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=basit
      - POSTGRES_PASSWORD=basit123
      - POSTGRES_DB=baroque
    ports:
      - 3002:3000
    command: npm run start
    depends_on:
      - migration

  baroque_db:
        image: postgres
        restart: always
        ports:
          - 5433:5432
        environment:
          - POSTGRES_USER=basit
          - POSTGRES_PASSWORD=basit123
          - POSTGRES_DB=baroque

  # The is added to ensure the migrations run as a separate service and not a regular thing to be done when server restarts

  migration:
    image: "node:8"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=basit
      - POSTGRES_PASSWORD=basit123
      - POSTGRES_DB=baroque
    volumes:
      - .:/app
    command: npm run seed 
    depends_on:
      - baroque_db
